ALTER TABLE NewsArticles ADD COLUMN api_id VARCHAR(100);
ALTER TABLE NewsArticles ADD CONSTRAINT uc_api_id UNIQUE (api_id);
ALTER TABLE NewsArticles MODIFY COLUMN created TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE NewsArticles MODIFY COLUMN modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;