ALTER TABLE NewsArticles MODIFY COLUMN title VARCHAR(500);
ALTER TABLE NewsArticles MODIFY COLUMN link VARCHAR(500);
ALTER TABLE NewsArticles MODIFY COLUMN video_url VARCHAR(500);
ALTER TABLE NewsArticles MODIFY COLUMN image_url VARCHAR(500);
ALTER TABLE NewsArticles MODIFY COLUMN source_id VARCHAR(500);
ALTER TABLE NewsArticles MODIFY COLUMN category VARCHAR(500);
ALTER TABLE NewsArticles MODIFY COLUMN country VARCHAR(500);

ALTER TABLE NewsArticles RENAME COLUMN `description` TO `content_description`;